const assert = require('node:assert/strict');
const {chromium} = require('playwright');
const fs = require('node:fs/promises');

(async () => {
  const browser = await chromium.launch({headless: true, ...(process.env.SABLE_TEST_BROWSER ? {executablePath: process.env.SABLE_TEST_BROWSER} : {})});
  try {
    const page = await browser.newPage({viewport: {width: 390, height: 844}});
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.route("**/ui/updates/automatic-check", route => route.fulfill({status: 202}), {times: 1});
    await page.goto(process.argv[2]);
    const notice = page.locator('[data-update-version]');
    await notice.waitFor();
    assert.equal(await page.locator('.toast-success').count(), 0, 'ordinary login does not report a completed update');
    assert.equal(await notice.locator('details').count(), 0, 'notification has no release notes disclosure');
    await notice.getByRole('button', {name: 'Release notes', exact: true}).click();
    const notesDialog = page.locator('#notification-release-notes-dialog');
    await notesDialog.waitFor({state: 'visible'});
    assert.match(await notesDialog.innerText(), /Rolling updates/);
    assert.equal(await notesDialog.locator("h3").innerText(), "Improvements", "release notes render Markdown headings");
    const releaseLink = await notesDialog.getByRole('link', {name: 'View release'}).boundingBox();
    const done = await notesDialog.getByRole('button', {name: 'Done', exact: true}).boundingBox();
    assert.ok(done.y >= releaseLink.y + releaseLink.height, 'Done follows View release on mobile');
    assert.equal(await page.evaluate(() => window.releaseNotesExecuted), undefined);
    assert.equal(await page.locator('.about-version-copy a').getAttribute('href'), 'https://github.com/drudge/sable/releases/tag/v1.0.0');
    const bounds = await notice.boundingBox();
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390, 'mobile notification fits the viewport');
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'release notes do not overflow');
    await notesDialog.getByRole('button', {name: 'Done', exact: true}).click();
    assert.equal(await notice.getByRole('button', {name: 'Release notes', exact: true}).evaluate(element => element === document.activeElement), true, 'closing notes restores focus');
    await page.locator('#about-update').getByRole('button', {name: 'Release notes', exact: true}).click();
    assert.equal(await page.locator('#update-release-notes-dialog .release-notes-content').innerHTML(), await notesDialog.locator('.release-notes-content').innerHTML(), 'About and notification use the same notes dialog content');
    await page.locator('#update-release-notes-dialog').getByRole('button', {name: 'Done', exact: true}).click();
    if (process.env.SABLE_UPDATE_SCREENSHOTS) {
      await fs.mkdir(process.env.SABLE_UPDATE_SCREENSHOTS, {recursive: true});
      await page.screenshot({path: `${process.env.SABLE_UPDATE_SCREENSHOTS}/notification-mobile.png`, fullPage: true});
    }
    await notice.locator('[data-toast-close]').click();
    await notice.waitFor({state: 'detached'});
    assert.equal(await notesDialog.count(), 0, 'dismissing the notification removes its dialog');
    await page.reload();
    assert.equal(await page.locator('[data-update-version]').count(), 0, 'dismissed notification is not repeated in the session');
    assert.equal(await (await page.request.get(`${process.argv[2]}/checks`)).json(), 1, 'same session does not recheck');
    await page.evaluate(() => sessionStorage.clear());
    await page.goto(`${process.argv[2]}/?disabled`);
    assert.equal(await (await page.request.get(`${process.argv[2]}/checks`)).json(), 1, 'opt-out prevents checks');
    await page.setViewportSize({width: 1440, height: 1000});
    await page.goto(`${process.argv[2]}/cluster?disabled`);
    const clusterCard = page.locator('.cluster-aside .cluster-update-card');
    assert.match(await clusterCard.innerText(), /ns3-latham/);
    const clusterBounds = await clusterCard.boundingBox();
    const localNodeBounds = await page.locator('.cluster-details').boundingBox();
    assert.ok(clusterBounds.y + clusterBounds.height <= localNodeBounds.y, 'rolling updates appear above Local Node');
    await clusterCard.getByRole('button', {name: 'Release notes', exact: true}).click();
    const clusterNotes = page.locator('#cluster-release-notes-dialog');
    await clusterNotes.waitFor({state: 'visible'});
    assert.match(await clusterNotes.locator('.release-notes-content').innerText(), /Rolling updates/);
    await page.waitForResponse(response => response.url().endsWith('/ui/cluster/status'));
    assert.equal(await clusterNotes.isVisible(), true, 'live refresh preserves the open release notes dialog');
    await clusterNotes.getByRole('button', {name: 'Done', exact: true}).click();
    await page.waitForResponse(response => response.url().endsWith('/ui/cluster/status'));
    assert.equal(await page.locator('#cluster-updates').count(), 1, 'live refresh replaces the sidebar without duplicating it');
    assert.equal(await clusterCard.isVisible(), true, 'rollout remains visible while a restarting node renegotiates support');
    assert.equal(await clusterCard.locator('.cluster-update-step .icon-loader-circle').count(), 1);
    assert.equal(await clusterCard.locator('.cluster-update-step .icon-check').count(), 1);
    assert.match(await clusterCard.locator('.cluster-update-version').innerText(), /v1\.1\.0/);
    assert.equal(await clusterCard.locator('.cluster-update-status').innerText(), 'Updating cluster');
    assert.equal(await page.locator('[hx-post="/ui/updates/cluster/stop"]').count(), 1);
    if (process.env.SABLE_UPDATE_SCREENSHOTS) await page.screenshot({path: `${process.env.SABLE_UPDATE_SCREENSHOTS}/cluster-desktop.png`, fullPage: true});
    const scopePage = await browser.newPage({viewport: {width: 320, height: 844}});
    scopePage.on('pageerror', error => errors.push(error.message));
    await scopePage.goto(`${process.argv[2]}/about?scope`);
    const scopeTrigger = scopePage.getByRole('button', {name: 'Choose update scope', exact: true});
    await scopeTrigger.waitFor();
    await scopePage.getByRole('button', {name: 'Update node', exact: true}).click();
    const scopeConfirmation = scopePage.locator('dialog.confirmation-dialog[open]');
    await scopeConfirmation.waitFor();
    assert.match(await scopeConfirmation.innerText(), /Install this release/);
    await scopeConfirmation.getByRole('button', {name: 'Cancel', exact: true}).click();
    await scopeTrigger.click();
    await scopeTrigger.click();
    assert.equal(await scopePage.locator('.update-scope-menu:popover-open').count(), 0, 'second click closes the scope menu');
    await scopeTrigger.focus();
    await scopeTrigger.press('ArrowUp');
    const scopeMenu = scopePage.getByRole('menu', {name: 'Update scope', exact: true});
    await scopeMenu.waitFor({state: 'visible'});
    const scopeBounds = await scopeMenu.boundingBox();
    assert.ok(scopeBounds.x >= 0 && scopeBounds.x + scopeBounds.width <= 320, 'scope menu fits narrow screens');
    assert.ok(scopeBounds.y >= 0 && scopeBounds.y + scopeBounds.height <= 844, 'scope menu opens above the notification');
    assert.match(await scopePage.locator(':focus').innerText(), /Update cluster/);
    await scopePage.keyboard.press('Escape');
    assert.equal(await scopeTrigger.getAttribute('aria-expanded'), 'false');
    assert.equal(await scopeTrigger.evaluate(element => element === document.activeElement), true);
    await scopeTrigger.click();
    await scopeMenu.getByRole('menuitem', {name: /Update cluster/}).click();
    await scopeConfirmation.waitFor();
    assert.equal(await scopeMenu.isVisible(), false, 'scope menu closes before confirmation');
    assert.match(await scopeConfirmation.innerText(), /Each replica restarts and synchronizes/);
    await scopeConfirmation.getByRole('button', {name: 'Cancel', exact: true}).click();
    assert.equal(await scopeTrigger.evaluate(element => element === document.activeElement), true, 'cancel returns focus to the scope picker');
    assert.equal(await (await page.request.get(`${process.argv[2]}/rollouts`)).json(), 0);
    await scopeTrigger.click();
    await scopeMenu.getByRole('menuitem', {name: /Update cluster/}).click();
    await scopeConfirmation.getByRole('button', {name: 'Start rolling update', exact: true}).click();
    await scopePage.waitForURL('**/cluster');
    assert.equal(await (await page.request.get(`${process.argv[2]}/rollouts`)).json(), 1);
    assert.equal(await (await page.request.get(`${process.argv[2]}/installs`)).json(), 0, 'cluster choice never calls the node installer');
    await scopePage.close();
    const installPage = await browser.newPage();
    installPage.on('pageerror', error => errors.push(error.message));
    await installPage.goto(`${process.argv[2]}/cluster`);
    await installPage.locator('[data-update-version]').getByRole('button', {name: 'Install v1.1.0', exact: true}).click();
    const confirmation = installPage.locator('dialog.confirmation-dialog[open]');
    await confirmation.waitFor({state: 'visible'});
    assert.equal(await (await page.request.get(`${process.argv[2]}/installs`)).json(), 0, 'install waits for confirmation');
    await confirmation.getByRole('button', {name: 'Download & Install', exact: true}).click();
    const installNotice = installPage.locator('[data-update-version]');
    const installing = installNotice.getByRole('button', {name: 'Installing…', exact: true});
    await installing.waitFor({state: 'visible'});
    assert.equal(await installing.isEnabled(), false, 'download cannot be started twice');
    assert.match(await installNotice.innerText(), /Downloading sable/);
    assert.equal(await installing.locator('.icon-refresh').evaluate(element => getComputedStyle(element).animationName), 'about-update-spin', 'download has a spinner');
    assert.equal(new URL(installPage.url()).pathname, '/cluster', 'install stays on the current page');
    await installNotice.getByRole('button', {name: 'Release notes', exact: true}).click();
    await installPage.locator('#notification-release-notes-dialog').getByRole('button', {name: 'Done', exact: true}).click();
    const restartButton = installNotice.getByRole('button', {name: 'Restart Sable', exact: true});
    await restartButton.waitFor({state: 'visible'});
    assert.match(await installNotice.innerText(), /Sable v1.1.0 is installed/);
    assert.equal(await (await page.request.get(`${process.argv[2]}/installs`)).json(), 1, 'notification installs from a page without an About panel');
    await restartButton.click();
    const restartConfirmation = installPage.locator('dialog.confirmation-dialog[open]');
    await restartConfirmation.waitFor({state: 'visible'});
    assert.equal(await (await page.request.get(`${process.argv[2]}/restarts`)).json(), 0, 'restart waits for confirmation');
    await Promise.all([
      installPage.waitForEvent('load'),
      restartConfirmation.getByRole('button', {name: 'Restart Sable', exact: true}).click(),
    ]);
    assert.equal(new URL(installPage.url()).pathname, '/cluster', 'restart returns to the same page');
    assert.equal(await (await page.request.get(`${process.argv[2]}/restarts`)).json(), 1, 'notification restarts once');
    const completedToast = installPage.locator('.toast-success');
    await completedToast.waitFor({state: 'visible'});
    assert.match(await completedToast.innerText(), /Sable was updated to v1\.1\.0\./);
    assert.equal(await completedToast.getAttribute('data-toast-duration'), '4500', 'completion toast dismisses automatically');
    await installPage.reload();
    assert.equal(await installPage.locator('.toast-success').count(), 0, 'completion toast is shown only once');
    await installPage.close();
    assert.deepEqual(errors, []);
    console.log('PASS login notice, release notes, escaping, release links, mobile layout, dismissal, opt-out, and cluster progress');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
